---
- name: Prob2 Playbook
  hosts: toy_srv_linux
  gather_facts: false

  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - jq

  - name: Deploy shell script
    ansible.builtin.copy:
      src: ./get_config
      dest: /app/get_config
      owner: root
      group: root
      mode: '0755'
    notify:
      - Run get_config

  handlers:
    - name: Run get_config
      ansible.builtin.shell: /app/get_config
      register: results
      notify: Print stdout

    - name: Print stdout
      ansible.builtin.debug:
        var: results.stdout

      
